spring:
  servlet:
    multipart:
      max-file-size: 40MB
      max-request-size: 40MB
  datasource:
    url: jdbc:postgresql://localhost:5432/photomap
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: update

app:
  storage:
    local-path: ${PHOTOS_PATH:/run/media/lillyrosebeaux/Windows8_OS/Photos/}